version: "3.9"

services:
  api:
    image: python:3.13
    container_name: vi-api
    working_dir: /opt/api
    command: bash -c "pip install pdm && pdm install && pdm run api --host 0.0.0.0"
    volumes:
      - ./api:/opt/api
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    profiles: ["", "dev"]
  front:
    container_name: vi-web
    build: ./front-js
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    profiles: [""]
  front-dev:
    container_name: vi-web-dev
    build:
      context: ./front-js
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/front-js/app
      - /front-js/app/node_modules
      - /front-js/app/.next
    ports:
      - 3000:3000
    profiles: ["dev"]

networks:
  app-network:
    driver: bridge
